import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
	linearGradient: {
		flex: 1,
	},
	mainFrame: {
		flexDirection: "column",
		padding: 32,
		marginTop: "5%",
	},
	welcomeMessageTitle: {
		fontSize: 32,
		fontWeight: "700",
		textAlign: "left",
		color: "#06283D",
		textShadowColor: "rgba(0, 0, 0, 0.75)",
		textShadowOffset: { width: -1, height: 1 },
		textShadowRadius: 10,
	},
	welcomeMessage: {
		fontSize: 18,
		fontWeight: "400",
		textAlign: "left",
		color: "#06283D",
		marginTop: 32,
	},
	campusHuntContainer: {
		marginTop: 32,
		flex: 1,
		height: 125,
		width: "100%",
		borderRadius: 12,
		borderTopLeftRadius: 64,
		borderBottomRightRadius: 64,
		borderWidth: 5,
		borderColor: "#256D85",
		justifyContent: "center",
		alignItems: "center",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.5,
		shadowRadius: 5,
		elevation: 5,
		shadowColor: "#171717",
	},
	campusHuntButtonContainer: {
		flex: 1,
		flexDirection: "row",
		width: "100%",
		height: "100%",
		borderRadius: 8,
		borderTopLeftRadius: 58,
		borderBottomRightRadius: 58,
		justifyContent: "center",
		alignItems: "center",
	},
	campusHuntButtonImage: {
		borderRadius: 8,
		borderTopLeftRadius: 58,
		borderBottomRightRadius: 58,
	},
	campusHunt: {
		fontSize: 28,
		fontWeight: "700",
		textAlign: "left",
		color: "#ffffff",
		textShadowColor: "#256D85",
		textShadowOffset: { width: 2, height: 2 },
		textShadowRadius: 1,
	},
	socContainer: {
		marginTop: 32,
		flex: 1,
		height: 125,
		width: "100%",
		borderRadius: 12,
		borderTopLeftRadius: 64,
		borderBottomRightRadius: 64,
		borderWidth: 5,
		borderColor: "#FF8787",
		justifyContent: "center",
		alignItems: "center",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.5,
		shadowRadius: 5,
		elevation: 5,
		shadowColor: "#171717",
	},
	socButtonContainer: {
		flex: 1,
		flexDirection: "row",
		width: "100%",
		height: "100%",
		borderRadius: 8,
		borderTopLeftRadius: 58,
		borderBottomRightRadius: 58,
		justifyContent: "center",
		alignItems: "center",
	},
	socButtonImage: {
		borderRadius: 8,
		borderTopLeftRadius: 58,
		borderBottomRightRadius: 58,
	},
	soc: {
		fontSize: 28,
		fontWeight: "700",
		textAlign: "left",
		color: "#ffffff",
		textShadowColor: "#FF8787",
		textShadowOffset: { width: 2, height: 2 },
		textShadowRadius: 1,
	},
	eventContainer: {
		marginTop: 32,
		flex: 1,
		height: 125,
		width: "100%",
		borderRadius: 12,
		borderTopLeftRadius: 64,
		borderBottomRightRadius: 64,
		borderWidth: 5,
		borderColor: "#7FB77E",
		justifyContent: "center",
		alignItems: "center",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.5,
		shadowRadius: 5,
		elevation: 5,
		shadowColor: "#171717",
	},
	eventButtonContainer: {
		flex: 1,
		flexDirection: "row",
		width: "100%",
		height: "100%",
		borderRadius: 8,
		borderTopLeftRadius: 58,
		borderBottomRightRadius: 58,
		justifyContent: "center",
		alignItems: "center",
	},
	eventButtonImage: {
		borderRadius: 8,
		borderTopLeftRadius: 58,
		borderBottomRightRadius: 58,
	},
	event: {
		fontSize: 28,
		fontWeight: "700",
		textAlign: "left",
		color: "#ffffff",
		textShadowColor: "#7FB77E",
		textShadowOffset: { width: 2, height: 2 },
		textShadowRadius: 1,
	},
});

export default styles;
